### ISSUE TITLE
パスワードのハッシュ化がレインボーハッシュテーブル攻撃にたいして脆弱

### ISSUE THREAD

**Issue by mikkame** [maritake/pets_open#1]
新規会員登録する際に、パスワードの保存形態を確認しようとしたところ、レインボーハッシュテーブル攻撃に対して脆弱であったため、お節介かもしれませんが起票させていただきます。

該当箇所
https://github.com/maritake/pets_open/blob/3a0ed898dc3a3c8721b8956890ea3a704634f945/join/index.php#L41

影響を受ける箇所
https://github.com/maritake/pets_open/blob/master/login.php#L10

レインボーハッシュテーブルについて
https://ja.wikipedia.org/wiki/%E3%83%AC%E3%82%A4%E3%83%B3%E3%83%9C%E3%83%BC%E3%83%86%E3%83%BC%E3%83%96%E3%83%AB

[password_hash](https://www.php.net/manual/ja/function.password-hash.php) 関数を使うと簡単に回避できます。

---

P.S.
他にも脆弱な場所がありますが、起票した方がよろしいでしょうか？（後学のため）、ご迷惑でしたらこのままCloseしてください。

**Comment by maritake** [comment]
@mikkame さん、初めまして。この度はコードレビューを頂きまして誠にありがとうございます。
sha1の脆弱性については存じ上げませんでしたので、大変勉強になりました。
ご指摘頂いた箇所につきまして、login.php、join/index.php、join/check.phpを以下のように修正いたしました。
https://github.com/maritake/pets_open/commit/cba0434b67486c1c9417e2a04ada6bc27b11e9d0

大変貴重なご意見を頂き、ありがとうございました。
また、その他の脆弱な箇所など、ご面倒でなければ是非ご教示頂きたく存じます。
どうぞよろしくお願いいたします。

**Comment by mikkame** [comment]
LGTMです！
お節介ではなさそうなので引き続きコメントさせて戴きます！

**Comment by maritake** [comment]
@mikkame さん
ありがとうございます！勉強させて頂きます！
お手数をおかけしますが、どうぞよろしくお願いいたします。
